# Generated by Django 5.1.4 on 2024-12-21 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mailing",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date_start", models.DateTimeField(blank=True, null=True, verbose_name="Дата начала рассылка")),
                ("date_finish", models.DateTimeField(blank=True, null=True, verbose_name="Дата конца рассылка")),
                (
                    "status_msg",
                    models.CharField(
                        choices=[("Создана", "Создана"), ("Завершена", "Завершена"), ("Запущена", "Запущена")],
                        verbose_name="статус сообщения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text_topic", models.TextField(blank=True, null=True, verbose_name="Текст письма")),
                ("text_body", models.CharField(blank=True, null=True, verbose_name="Текст")),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
        migrations.CreateModel(
            name="Receiver",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(max_length=254, unique=True, verbose_name="email")),
                ("name", models.CharField(blank=True, null=True, verbose_name="ФИО")),
                ("description", models.TextField(blank=True, null=True, verbose_name="Описание")),
            ],
            options={
                "verbose_name": "Получатель рассылки",
                "verbose_name_plural": "Получатели рассылки",
            },
        ),
        migrations.CreateModel(
            name="MailingAttempt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date_attempt", models.DateTimeField(blank=True, null=True, verbose_name="Дата и время попытки")),
                (
                    "status_attempt",
                    models.CharField(
                        choices=[("Успешно", "Успешно"), ("Не успешно", "Не успешно")], verbose_name="статус сообщения"
                    ),
                ),
                ("answer_attempt", models.TextField(blank=True, null=True, verbose_name="Текст")),
                (
                    "mailing_attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mailing",
                        to="spam_mailing.mailing",
                        verbose_name="Расслылка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Попытка расслыки",
                "verbose_name_plural": "Попытки рассылки",
            },
        ),
        migrations.AddField(
            model_name="mailing",
            name="text_msg",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="message",
                to="spam_mailing.message",
                verbose_name="Сообщение",
            ),
        ),
        migrations.AddField(
            model_name="mailing",
            name="receivers_msgs",
            field=models.ManyToManyField(
                related_name="receiver", to="spam_mailing.receiver", verbose_name="Получатели"
            ),
        ),
    ]
