# Generated by Django 5.1.4 on 2025-01-23 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spam_mailing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="date_finish",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Дата конца рассылки"),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="date_start",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Дата начала рассылки"),
        ),
    ]
