# Generated by Django 5.1.4 on 2025-01-24 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("spam_mailing", "0002_alter_mailing_date_finish_alter_mailing_date_start"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mailing",
            old_name="date_finish",
            new_name="date_end",
        ),
        migrations.RenameField(
            model_name="mailing",
            old_name="status_msg",
            new_name="status",
        ),
        migrations.RenameField(
            model_name="mailingattempt",
            old_name="answer_attempt",
            new_name="mail_response",
        ),
        migrations.RenameField(
            model_name="mailingattempt",
            old_name="mailing_attempt",
            new_name="mailing",
        ),
        migrations.RenameField(
            model_name="mailingattempt",
            old_name="status_attempt",
            new_name="status",
        ),
    ]
