# Generated by Django 5.1.4 on 2025-01-26 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("spam_mailing", "0004_mailing_owner_mailingattempt_owner_message_owner_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "permissions": [("can_view_mailing", "can_view_mailing")],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="receiver",
            options={
                "permissions": [("can_view_reciever", "can_view_reciever")],
                "verbose_name": "Получатель рассылки",
                "verbose_name_plural": "Получатели рассылки",
            },
        ),
    ]
